
services:
  frontend:
    build: .
    restart: unless-stopped
    ports:
      - "4200:4200"
#    volumes:
#      - ./:/app
#      - /app/node_modules
    environment:
      - API_URL=http://localhost:3000/api
